{% set name = "harlequin-mysql" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/harlequin_mysql-{{ version }}.tar.gz
  sha256: 7a5a82e5c2eb9383a30443d387a139a4509b111afc2fe935b619e6c73409ee7b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0
    - harlequin >=1.25.0,<3
    - mysql-connector-python >=9.1.0,<10.0.0

test:
  imports:
    - harlequin_mysql
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tconbeer/harlequin-mysql
  summary: A Harlequin adapter for MySQL.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/harlequin
