{% set name = "harlequin-mysql" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/harlequin_mysql-{{ version }}.tar.gz
  sha256: 8e1f8d391e0980bcb6fa257aca939a4ef35f0fa699fad9a03e4835169b6f4585

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0
    - harlequin >=1.7,<3
    - mysql-connector-python >=8.2.0,<9.0.0

test:
  imports:
    - harlequin_mysql
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tconbeer/harlequin-mysql
  summary: A Harlequin adapter for MySQL.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/harlequin
