schema_version: 1

context:
  name: harlequin-mysql
  version: 1.4.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/harlequin_mysql-${{ version }}.tar.gz
  sha256: 60eb100978711c4f8a6e1b702d7fed313f298b2b0641eed259a5415673f75d25

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - harlequin >=2.11.0,<3
    - mysql-connector-python >=9.1.0,<10
tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - harlequin_mysql

about:
  summary: A Harlequin adapter for MySQL.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/tconbeer/harlequin-mysql

extra:
  recipe-maintainers:
    - conda-forge/harlequin
